-- Logical chunk identities and their physical encodings have separate lifetimes.
CREATE TABLE chunk_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id bigint NOT NULL REFERENCES chunks ON DELETE CASCADE,
    storage_id uuid NOT NULL UNIQUE,
    stored_size integer,
    compressed boolean NOT NULL,
    nonce bytea,
    state text NOT NULL CHECK (state IN ('uploading','ready','retired','deleting','deleted')),
    created_at timestamptz NOT NULL,
    unreferenced_at timestamptz,
    deleted_at timestamptz
);
INSERT INTO chunk_locations(id,chunk_id,storage_id,stored_size,compressed,nonce,state,created_at,unreferenced_at,deleted_at)
SELECT id,id,storage_id,stored_size,compressed,nonce,
       CASE state WHEN 'ready' THEN 'ready' WHEN 'deleted' THEN 'deleted'
            WHEN 'deleting' THEN 'deleting' ELSE 'retired' END,
       created_at,unreferenced_at,deleted_at FROM chunks;
SELECT setval(pg_get_serial_sequence('chunk_locations','id'),GREATEST(COALESCE(max(id),0),(SELECT last_value FROM chunks_id_seq),1),true) FROM chunks;
ALTER TABLE chunks ADD COLUMN encoding_id bigint;
UPDATE chunks SET encoding_id=id;
ALTER TABLE chunks ALTER COLUMN encoding_id SET NOT NULL;
ALTER TABLE chunks ALTER COLUMN encoding_id SET DEFAULT nextval('chunk_locations_id_seq');
CREATE UNIQUE INDEX chunk_locations_current ON chunk_locations(chunk_id) WHERE state='ready';
CREATE INDEX chunk_locations_gc ON chunk_locations(unreferenced_at,id) WHERE state IN ('retired','deleting');

CREATE TABLE packs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    storage_id uuid NOT NULL UNIQUE,
    algorithm text NOT NULL CHECK (algorithm IN ('none','aes-256-gcm','chacha20-poly1305')),
    key_id text NOT NULL,
    raw_size bigint NOT NULL CHECK (raw_size>0),
    stored_size bigint,
    compressed boolean NOT NULL DEFAULT false,
    nonce bytea CHECK (nonce IS NULL OR octet_length(nonce)=12),
    digest bytea CHECK (digest IS NULL OR octet_length(digest)=32),
    member_count integer NOT NULL CHECK (member_count>=2),
    state text NOT NULL CHECK (state IN ('preparing','ready','retired','deleting','deleted')),
    created_at timestamptz NOT NULL DEFAULT now(),
    unreferenced_at timestamptz,
    deleted_at timestamptz
);
ALTER TABLE chunks ADD COLUMN pack_id bigint REFERENCES packs;
CREATE INDEX chunks_pack ON chunks(pack_id) WHERE pack_id IS NOT NULL;
CREATE TABLE pack_members (
    pack_id bigint NOT NULL REFERENCES packs ON DELETE CASCADE,
    ordinal integer NOT NULL CHECK (ordinal>=0),
    chunk_id bigint NOT NULL REFERENCES chunks ON DELETE CASCADE,
    offset_bytes bigint NOT NULL CHECK (offset_bytes>=0),
    PRIMARY KEY(pack_id,ordinal),
    UNIQUE(pack_id,chunk_id)
);
CREATE INDEX pack_members_chunk ON pack_members(chunk_id);
CREATE INDEX packs_gc ON packs(unreferenced_at,id) WHERE state IN ('retired','deleting');

CREATE TABLE pack_maintenance (
    stream_id uuid PRIMARY KEY REFERENCES streams ON DELETE CASCADE,
    cursor bigint NOT NULL DEFAULT 0,
    generation bigint NOT NULL DEFAULT 1,
    next_check_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    reason text NOT NULL DEFAULT 'pack'
);
CREATE INDEX pack_maintenance_due ON pack_maintenance(next_check_at,stream_id);
CREATE TABLE pack_changes (
    pack_id bigint PRIMARY KEY REFERENCES packs ON DELETE CASCADE,
    generation bigint NOT NULL DEFAULT 1,
    next_check_at timestamptz NOT NULL DEFAULT now(),
    reason text NOT NULL DEFAULT 'reuse' CHECK(reason IN ('reuse','reclaim'))
);
CREATE INDEX pack_changes_due ON pack_changes(reason,next_check_at,pack_id);
CREATE TABLE pack_inputs (
    task_id uuid NOT NULL REFERENCES tasks ON DELETE CASCADE,
    chunk_id bigint NOT NULL REFERENCES chunks,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(task_id,chunk_id)
);
CREATE UNIQUE INDEX pack_inputs_chunk ON pack_inputs(chunk_id);
CREATE TABLE integrity_packs (
    task_id uuid NOT NULL REFERENCES tasks ON DELETE CASCADE,
    pack_id bigint NOT NULL REFERENCES packs ON DELETE CASCADE,
    error_code text,
    PRIMARY KEY(task_id,pack_id)
);
ALTER TABLE packs ADD COLUMN owner_task uuid REFERENCES tasks ON DELETE SET NULL;
ALTER TABLE chunk_locations ADD COLUMN owner_task uuid REFERENCES tasks ON DELETE SET NULL;
ALTER TABLE chunks ADD COLUMN reference_changed_at timestamptz NOT NULL DEFAULT now();

-- Changes, including multipart boundary replacement, enqueue work in the same transaction.
CREATE FUNCTION enqueue_pack_extents() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM id FROM chunks WHERE id IN (SELECT chunk_id FROM changed) ORDER BY id FOR UPDATE;
    UPDATE chunks SET reference_changed_at=now() WHERE id IN (SELECT chunk_id FROM changed);
    INSERT INTO pack_changes(pack_id,reason)
        SELECT DISTINCT c.pack_id,CASE WHEN TG_OP='DELETE' THEN 'reclaim' ELSE 'reuse' END FROM changed e JOIN chunks c ON c.id=e.chunk_id WHERE c.pack_id IS NOT NULL
        ON CONFLICT(pack_id) DO UPDATE SET generation=pack_changes.generation+1,next_check_at=now(),reason=CASE WHEN EXCLUDED.reason='reuse' THEN 'reuse' ELSE pack_changes.reason END;
    INSERT INTO pack_maintenance(stream_id,reason)
        SELECT DISTINCT e.stream_id,'repack' FROM changed x JOIN extents e ON e.chunk_id=x.chunk_id
        JOIN streams s ON s.id=e.stream_id WHERE s.state='ready'
        ON CONFLICT(stream_id) DO UPDATE SET generation=pack_maintenance.generation+1,cursor=0,updated_at=now(),next_check_at=now();
    RETURN NULL;
END $$;
CREATE TRIGGER pack_extents_insert AFTER INSERT ON extents REFERENCING NEW TABLE AS changed FOR EACH STATEMENT EXECUTE FUNCTION enqueue_pack_extents();
CREATE TRIGGER pack_extents_delete AFTER DELETE ON extents REFERENCING OLD TABLE AS changed FOR EACH STATEMENT EXECUTE FUNCTION enqueue_pack_extents();
CREATE TRIGGER pack_extents_update AFTER UPDATE ON extents REFERENCING NEW TABLE AS changed FOR EACH STATEMENT EXECUTE FUNCTION enqueue_pack_extents();
CREATE FUNCTION enqueue_pack_stream() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.state='ready' AND OLD.state IS DISTINCT FROM NEW.state THEN
        INSERT INTO pack_maintenance(stream_id) SELECT NEW.id WHERE NEW.kind='object' AND EXISTS(SELECT 1 FROM extents WHERE stream_id=NEW.id AND chunk_id IS NOT NULL OFFSET 1)
            ON CONFLICT(stream_id) DO UPDATE SET generation=pack_maintenance.generation+1,cursor=0,reason='pack',updated_at=now(),next_check_at=now();
        INSERT INTO pack_changes(pack_id)
            SELECT DISTINCT c.pack_id FROM extents e JOIN chunks c ON c.id=e.chunk_id WHERE e.stream_id=NEW.id AND c.pack_id IS NOT NULL
            ON CONFLICT(pack_id) DO UPDATE SET generation=pack_changes.generation+1,next_check_at=now(),reason='reuse';
    END IF;
    RETURN NULL;
END $$;
CREATE TRIGGER pack_stream_ready AFTER UPDATE OF state ON streams FOR EACH ROW EXECUTE FUNCTION enqueue_pack_stream();
INSERT INTO pack_maintenance(stream_id) SELECT stream_id FROM objects WHERE stream_id IS NOT NULL ON CONFLICT DO NOTHING;
CREATE TABLE chunk_access_stats (
    chunk_id bigint PRIMARY KEY REFERENCES chunks ON DELETE CASCADE,
    reads bigint NOT NULL DEFAULT 0,
    range_reads bigint NOT NULL DEFAULT 0,
    bytes bigint NOT NULL DEFAULT 0,
    last_read_at timestamptz NOT NULL
);
CREATE TABLE chunk_access_windows (
    chunk_id bigint NOT NULL REFERENCES chunks ON DELETE CASCADE,
    window_start timestamptz NOT NULL,
    reads bigint NOT NULL DEFAULT 0,
    range_reads bigint NOT NULL DEFAULT 0,
    bytes bigint NOT NULL DEFAULT 0,
    range_origin_reads bigint NOT NULL DEFAULT 0,
    PRIMARY KEY(window_start,chunk_id)
);
CREATE TABLE pack_access_windows (
    pack_id bigint NOT NULL REFERENCES packs ON DELETE CASCADE,
    window_start timestamptz NOT NULL,
    downloads bigint NOT NULL DEFAULT 0,
    downloaded_bytes bigint NOT NULL DEFAULT 0,
    partial_downloads bigint NOT NULL DEFAULT 0,
    useful_bytes bigint NOT NULL DEFAULT 0,
    PRIMARY KEY(window_start,pack_id)
);
CREATE INDEX chunk_access_history ON chunk_access_windows(chunk_id,window_start);
CREATE INDEX pack_access_history ON pack_access_windows(pack_id,window_start);
ALTER TABLE gateway_meta ADD COLUMN access_coverage_since timestamptz NOT NULL DEFAULT now();
ALTER TABLE gateway_meta ADD COLUMN access_flushed_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE chunks ADD COLUMN split_at timestamptz;
ALTER TABLE chunks ADD COLUMN range_split_at timestamptz;
ALTER TABLE chunks ADD COLUMN repack_after timestamptz;
ALTER TABLE tasks DROP CONSTRAINT tasks_kind_check;
ALTER TABLE tasks ADD CHECK (kind IN ('purge','sweep','integrity','pack','unpack'));
UPDATE gateway_meta SET schema_version=5;
