"""Prepare the vendored Resource Han Rounded CN WOFF2 subsets."""

import argparse
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source", type=Path, help="Directory containing the upstream CN TTF files")
args = parser.parse_args()
web = Path(__file__).resolve().parents[1]
output = web / "src/fonts/resource-han-rounded"
output.mkdir(parents=True, exist_ok=True)
source = TTFont(args.source / "ResourceHanRoundedCN-Regular.ttf")
supported = set(source.getBestCmap())
common = supported & {ord(char) for char in (web / "src/locales/i18n.zh-CN.js").read_text()}
remaining = sorted(supported - common)
groups = [("ui", sorted(common))] + [
    (f"{index // 512:03}", remaining[index : index + 512])
    for index in range(0, len(remaining), 512)
]


def ranges(points):
    first = last = points[0]
    values = []
    for point in points[1:]:
        if point != last + 1:
            values.append(f"U+{first:X}" if first == last else f"U+{first:X}-{last:X}")
            first = point
        last = point
    values.append(f"U+{first:X}" if first == last else f"U+{first:X}-{last:X}")
    return ",".join(values)


rules = ["/* Generated by scripts/subset-font.py; see README.md and OFL.txt. */"]
for weight, variant in [(400, "Regular"), (500, "Medium"), (700, "Bold")]:
    for name, points in groups:
        font = TTFont(args.source / f"ResourceHanRoundedCN-{variant}.ttf", recalcTimestamp=False)
        options = subset.Options()
        options.name_IDs = ["*"]
        options.name_legacy = True
        options.name_languages = ["*"]
        job = subset.Subsetter(options=options)
        job.populate(unicodes=points)
        job.subset(font)
        font.flavor = "woff2"
        filename = f"resource-han-rounded-cn-{name}-{weight}.woff2"
        font.save(output / filename)
        rules.append(
            "@font-face {\n"
            "  font-family: 'Resource Han Rounded CN';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('./{filename}') format('woff2');\n"
            f"  unicode-range: {ranges(points)};\n"
            "}"
        )
        print(f"{name}/{weight}: {len(points)} code points, {(output / filename).stat().st_size} bytes", flush=True)
(output / "index.css").write_text("\n\n".join(rules) + "\n")
