import { execFileSync } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import openapiTS, { astToString } from 'openapi-typescript'

const schema = process.env.MOKYU_API_SCHEMA
  ? await readFile(process.env.MOKYU_API_SCHEMA, 'utf8')
  : execFileSync(process.env.MOKYU_BINARY || '../target/debug/mokyu', ['api-schema'], { encoding: 'utf8' })
const types = astToString(await openapiTS(JSON.parse(schema)))
await writeFile('src/api/schema.d.ts', '// Generated by npm run api:types from mokyu api-schema.\n' + types)
