import { readFileSync } from 'node:fs'
import { test, expect, type Page } from '@playwright/test'
import zh from '../src/locales/i18n.zh-CN.js'
import ja from '../src/locales/i18n.ja.js'
test.beforeEach(async ({ request }) => {
  const password = process.env.MOKYU_TEST_PASSWORD || readFileSync(process.env.MOKYU_TEST_PASSWORD_FILE!, 'utf8').trim()
  const login = await request.post('/api/login', { headers: { Origin: process.env.MOKYU_TEST_WEB! }, data: { username: 'tester', password } })
  expect(login.ok()).toBe(true)
  const headers = { Origin: process.env.MOKYU_TEST_WEB!, 'X-CSRF-Token': (await login.json()).csrf_token }
  expect((await request.put('/api/me', { headers, data: { display_name: '', locale: 'en', theme: 'light', avatar_email: '', avatar_enabled: false } })).ok()).toBe(true)
  await request.post('/api/logout', { headers })
})

async function login(page: Page) {
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Username', exact: true }).fill('tester')
  const password = process.env.MOKYU_TEST_PASSWORD || readFileSync(process.env.MOKYU_TEST_PASSWORD_FILE!, 'utf8')
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill(password.trim())
  await page.getByRole('button', { name: 'Come on in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Media library', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'media Active', exact: true }).click()
  await expect(page.getByRole('button', { name: 'small-part', exact: true })).toBeVisible()
}

test('styled select, drawer, focus restoration, notification and persisted theme', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error' && /Content Security Policy|Refused to/i.test(message.text())) errors.push(message.text()) })
  await login(page)
  await expect(page.locator('select')).toHaveCount(0)
  const select = page.getByRole('combobox', { name: 'Page size' })
  await select.click()
  await expect(page.getByRole('listbox')).toHaveCSS('border-radius', '15px')
  await expect(page.getByRole('option', { name: '100 per page', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(page.getByRole('option', { name: '50 per page', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(select).toContainText('50 per page')
  await expect(select).toBeFocused()
  const object = page.getByRole('button', { name: 'small-part', exact: true })
  await object.click()
  await expect(page.getByRole('dialog', { name: 'small-part' })).toBeVisible()
  await page.getByRole('tab', { name: 'Access', exact: true }).click()
  await expect(page.getByRole('tabpanel')).toContainText('Authorized requests only')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(object).toBeFocused()
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByText('Your collection is up to date', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Switch to dark', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('button', { name: 'small-part', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('account locale, appearance, profile guard and avatar fallback', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page)
  await page.getByRole('button', { name: 'Account menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Personal settings', exact: true }).click()
  await page.getByRole('textbox', { name: 'Display name', exact: true }).fill('Mochi keeper')
  await page.getByRole('link', { name: 'Media library', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Leave these changes behind?' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep editing', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('All tucked away', { exact: true }).first()).toBeVisible()
  await page.getByRole('combobox', { name: 'Appearance', exact: true }).click()
  await page.getByRole('option', { name: 'Dark', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Language', exact: true }).click()
  await page.getByRole('menuitem', { name: zh['language_zh-CN'], exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.getByRole('heading', { name: zh.account, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await page.getByRole('button', { name: zh.language, exact: true }).click()
  await page.getByRole('menuitem', { name: ja.language_ja, exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja')
  await page.getByRole('button', { name: ja.language, exact: true }).click()
  await page.getByRole('menuitem', { name: 'English', exact: true }).click()
  await page.getByRole('textbox', { name: 'Gravatar email', exact: true }).fill('missing-avatar@example.test')
  await page.getByRole('switch', { name: 'Use my Gravatar', exact: true }).click()
  await page.route('https://www.gravatar.com/**', route => route.fulfill({ status: 404 }))
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.locator('.profile-intro .avatar-fallback')).toHaveText('MK')
  await expect(page.getByText('This session', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('mobile navigation and drawer stay inside the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await login(page)
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Your workspace' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'small-part', exact: true }).click()
  const bounds = await page.getByRole('dialog', { name: 'small-part' }).boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'small-part', exact: true })).toBeFocused()
})
