import { readFileSync } from 'node:fs'
import { test, expect } from '@playwright/test'
import en from '../src/locales/i18n.en.js'

test('maintenance policies, task history, service configuration and key generation', async ({ page, request }) => {
  test.setTimeout(60000)
  const password = (process.env.MOKYU_TEST_PASSWORD || readFileSync(process.env.MOKYU_TEST_PASSWORD_FILE!, 'utf8')).trim()
  const login = await request.post('/api/login', { headers: { Origin: process.env.MOKYU_TEST_WEB! }, data: { username: 'tester', password } })
  const headers = { Origin: process.env.MOKYU_TEST_WEB!, 'X-CSRF-Token': (await login.json()).csrf_token }
  await request.put('/api/me', { headers, data: { display_name: '', locale: 'en', theme: 'light', avatar_email: '', avatar_enabled: false } })
  const before = await (await request.get('/api/maintenance')).json()
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/login')
  await page.getByRole('textbox', { name: en.username, exact: true }).fill('tester')
  await page.getByRole('textbox', { name: en.password, exact: true }).fill(password)
  await page.getByRole('button', { name: en.signIn, exact: true }).click()
  await expect(page).toHaveURL(/\/overview$/); await page.goto('/media')
  try {
    await page.goto('/maintenance'); await expect(page.locator('.policy-card')).toHaveCount(7)
    const cleanup = page.locator('.policy-card').filter({ has: page.getByRole('heading', { name: en.task_cleanup, exact: true }) })
    await cleanup.getByRole('button', { name: before.controls.find((p: any) => p.kind === 'cleanup').paused ? en.resumePolicy : en.pausePolicy, exact: true }).click()
    await expect(cleanup.getByRole('button', { name: before.controls.find((p: any) => p.kind === 'cleanup').paused ? en.pausePolicy : en.resumePolicy, exact: true })).toBeVisible()
    await request.post('/api/maintenance/cleanup/actions', { headers, data: { action: 'resume' } })
    await page.reload(); await cleanup.getByRole('button', { name: en.runNow, exact: true }).click()
    await expect(page.getByRole('dialog', { name: en.taskDetails, exact: true })).toBeVisible()
    await expect(page.locator('.task-hero')).toContainText(en.task_cleanup)
    await page.keyboard.press('Escape')
    await page.getByRole('combobox', { name: en.taskType, exact: true }).click()
    await page.getByRole('option', { name: en.task_cleanup, exact: true }).click()
    await expect(page.locator('.task-row').first()).toContainText(en.task_cleanup)
    await page.goto('/maintenance'); await page.getByRole('button', { name: en.integrityCheck, exact: false }).click()
    await page.getByRole('combobox', { name: en.inspectionDepth, exact: true }).click()
    await expect(page.getByRole('option', { name: en.integrity_head, exact: false })).toBeVisible()
    await page.keyboard.press('Escape'); await page.keyboard.press('Escape')
    await page.setViewportSize({ width: 1440, height: 1040 })
    await page.screenshot({ path: '/results/step16-maintenance.png', fullPage: true })
    await page.goto('/service'); await expect(page.locator('.queue-card')).toHaveCount(3)
    await expect(page.locator('.service-metric')).toHaveCount(3)
    await page.getByRole('tab', { name: en.runtimeConfig, exact: true }).click()
    await page.getByRole('textbox', { name: en.searchConfiguration }).fill('backend.secret_key')
    await expect(page.locator('.config-fields article')).toHaveCount(2)
    await expect(page.locator('.config-fields article').first()).toContainText(en.redactedValue)
    await page.getByRole('tab', { name: en.administratorTools, exact: true }).click()
    await page.getByRole('button', { name: en.generateKeyMaterial, exact: true }).click()
    const auth = page.getByRole('dialog').filter({ has: page.getByRole('textbox', { name: en.currentPassword, exact: true }) })
    await expect(auth.or(page.getByRole('dialog', { name: en.saveSecret, exact: true }))).toBeVisible()
    if (await auth.isVisible()) { await auth.getByRole('textbox', { name: en.currentPassword, exact: true }).fill(password); await auth.getByRole('button', { name: en.continue, exact: true }).click() }
    const secret = page.getByRole('dialog', { name: en.saveSecret, exact: true })
    await expect(secret).toBeVisible(); await expect(secret.getByRole('textbox', { name: en.secretValue })).toHaveValue(/^[a-f0-9]{64}$/)
    await page.keyboard.press('Escape'); await expect(secret).toBeVisible()
    await secret.getByRole('checkbox', { name: en.secretSaved }).check(); await secret.getByRole('button', { name: en.done, exact: true }).click()
    await page.goto('/maintenance'); await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.locator('.policy-card')).toHaveCount(7)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: '/results/step16-maintenance-mobile.png', fullPage: true })
    expect(errors).toEqual([])
  } finally { await request.post('/api/maintenance/cleanup/actions', { headers, data: { action: before.controls.find((p: any) => p.kind === 'cleanup').paused ? 'pause' : 'resume' } }) }
})
