<script setup lang="ts">
import { computed } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { Heart, Images, HardDrive, Sparkles, ArrowUpRight, Package, CloudUpload, RefreshCw, Archive, Flower2, Activity, Clock3 } from 'lucide-vue-next'
import { api, bytes, session, type Bucket } from '../api/client'
import { useInsights, taskTone, type Runtime } from '../app/insights'
import { t, date } from '../app/i18n'
import { report, errorText, notify } from '../app/feedback'
import ScopePicker from '../components/ScopePicker.vue'
import SpaceStory from '../components/SpaceStory.vue'
import TrendChart from '../components/TrendChart.vue'
import { jobIcon } from '../app/maintenance'
import EmptyState from '../components/EmptyState.vue'
const admin = computed(() => session.value?.role === 'admin')
const { scope, statistics } = useInsights(), usage = computed(() => statistics.data.value?.usage)
const runtime = useQuery({ queryKey: ['runtime-insights'], enabled: admin, queryFn: ({ signal }) => api<Runtime>('/api/insights/runtime', { signal }), refetchInterval: 15_000 })
const buckets = useQuery({ queryKey: ['buckets'], queryFn: ({ signal }) => api<Bucket[]>('/api/buckets', { signal }) })
const homes = computed(() => (buckets.data.value || []).filter(b => (!scope.value.bucket || b.id === scope.value.bucket) && (!scope.value.project || b.project_id === scope.value.project)).slice(0, 6))
const now = computed(() => runtime.data.value?.current)
const hitRate = computed(() => now.value && Number(now.value.cache_lookups) ? Math.round(Number(now.value.cache_hits) / Number(now.value.cache_lookups) * 1000) / 10 : null)
const capacity = computed(() => (statistics.data.value?.history || []).map(p => ({ at: p.at, value: Number(p.usage.logical_bytes) })))
const requests = computed(() => (runtime.data.value?.history || []).map((p, i, all) => { const previous = all[i - 1], seconds = previous ? (new Date(p.at).getTime() - new Date(previous.at).getTime()) / 1000 : 0; return { at: p.at, epoch: p.epoch, value: previous?.epoch === p.epoch && seconds > 0 && Number(p.requests) >= Number(previous.requests) ? (Number(p.requests) - Number(previous.requests)) / seconds : null } }))
const saving = computed(() => usage.value?.encoded_bytes == null ? null : Number(usage.value.logical_bytes) - Number(usage.value.encoded_bytes))
const packed = computed(() => usage.value && Number(usage.value.unique_bytes) ? Math.round(Number(usage.value.packed_bytes) / Number(usage.value.unique_bytes) * 100) : 0)
async function refresh() { const result = await statistics.refetch(); if (admin.value) await runtime.refetch(); if (result.error) report(result.error); else notify(t('refreshed')) }
</script>
<template>
  <div class="page-heading"><div><p class="eyebrow">{{ t('overviewEyebrow') }}</p><h1>{{ t('welcomeHome', { name: session?.display_name || session?.username || 'Mokyu' }) }} <Heart class="heading-heart" :size="24" /></h1><p>{{ t('overviewHint') }}</p></div><div class="heading-actions"><ScopePicker /><button class="icon-button" :aria-label="t('refresh')" :disabled="statistics.isFetching.value" @click="refresh"><RefreshCw :size="17" /></button></div></div>
  <p v-if="statistics.error.value || runtime.error.value" class="error" role="alert">{{ errorText(statistics.error.value || runtime.error.value) }}</p>
  <div v-if="statistics.data.value?.stale && usage" class="snapshot-note"><Clock3 :size="14" />{{ t('snapshotStale') }}</div>
  <div v-if="runtime.data.value && Number(runtime.data.value.failed_uploads) > 0" class="info-callout"><CloudUpload :size="20" /><p>{{ t('uploadNeedsAttention', { count: runtime.data.value.failed_uploads }) }}</p><RouterLink class="button" to="/transfers">{{ t('transfers') }}<ArrowUpRight :size="15" /></RouterLink></div>
  <div class="insight-cards">
    <RouterLink :to="{ path: '/storage', query: scope }" class="insight-card rose"><span class="metric-icon"><Images :size="23" /></span><small>{{ t('logicalMedia') }}</small><strong>{{ usage ? bytes(Number(usage.logical_bytes)) : '—' }}</strong><span>{{ usage ? t('objectsKept', { count: usage.objects }) : t('collectingInsights') }}</span><ArrowUpRight class="metric-link" :size="17" /></RouterLink>
    <RouterLink :to="{ path: '/storage', query: scope }" class="insight-card lilac"><span class="metric-icon"><HardDrive v-if="usage?.physical" :size="23" /><Sparkles v-else :size="23" /></span><small>{{ t(usage?.physical ? 'indexedBackend' : saving != null && saving < 0 ? 'extraEncoding' : 'spaceSaved') }}</small><strong>{{ usage?.physical ? bytes(Number(usage.physical.indexed_bytes)) : saving == null ? '—' : bytes(Math.abs(saving)) }}</strong><span>{{ t(usage?.physical ? 'indexedBackendHint' : 'attributionEstimate') }}</span><ArrowUpRight class="metric-link" :size="17" /></RouterLink>
    <RouterLink :to="{ path: '/storage', query: scope }" class="insight-card mint"><span class="metric-icon"><Archive v-if="admin" :size="23" /><Package v-else :size="23" /></span><small>{{ t(admin ? 'cacheHitRate' : 'packedContent') }}</small><strong>{{ admin ? hitRate == null ? '—' : hitRate + '%' : usage ? packed + '%' : '—' }}</strong><span>{{ admin ? t('deploymentSinceStart') : usage ? t('packsInScope', { count: usage.packs }) : t('collectingInsights') }}</span><ArrowUpRight class="metric-link" :size="17" /></RouterLink>
    <RouterLink to="/transfers" class="insight-card cream"><span class="metric-icon"><CloudUpload :size="23" /></span><small>{{ t('waitingForBackend') }}</small><strong>{{ admin && runtime.data.value ? bytes(Number(runtime.data.value.pending_bytes)) : usage ? bytes(Number(usage.pending_bytes)) : '—' }}</strong><span>{{ t(admin ? 'pendingCachePhysical' : 'pendingReferencedContent') }}</span><ArrowUpRight class="metric-link" :size="17" /></RouterLink>
  </div>
  <section class="surface insight-story"><div class="section-heading"><h2><Sparkles :size="19" />{{ t('roomForMore') }}</h2><span v-if="statistics.data.value?.as_of" class="field-help">{{ t('measuredAt', { time: date(statistics.data.value.as_of) }) }}</span></div><SpaceStory v-if="usage" :usage="usage" /><EmptyState v-else compact :title="t('collectingInsights')" :description="t('insightsWait')" /></section>
  <div class="overview-grid">
    <section class="surface overview-panel mint-panel"><div class="section-heading"><h2><Archive :size="19" />{{ t(admin ? 'localPantry' : 'packedTogether') }}</h2><RouterLink :to="{ path: '/storage', query: scope }" class="text-button">{{ t('takeALook') }}<ArrowUpRight :size="15" /></RouterLink></div><template v-if="admin && now"><div class="pantry-reading"><strong>{{ bytes(Number(now.cache_bytes)) }}</strong><span>/ {{ bytes(Number(now.cache_limit)) }}</span></div><div class="pantry-meter" role="progressbar" :aria-label="t('chunkCache')" :aria-valuenow="Math.min(100, Math.round(Number(now.cache_bytes) / Math.max(1, Number(now.cache_limit)) * 100))" aria-valuemin="0" aria-valuemax="100"><span :style="{ width: Math.min(100, Number(now.cache_bytes) / Math.max(1, Number(now.cache_limit)) * 100) + '%' }" /></div><div class="pantry-rows"><span>{{ t('uploadCache') }}<strong>{{ bytes(Number(now.upload_bytes)) }} / {{ bytes(Number(now.upload_limit)) }}</strong></span><span>{{ t('thumbnailCache') }}<strong>{{ bytes(Number(now.thumbnail_bytes)) }}</strong></span></div><p class="field-help">{{ t('cacheOverlapHint') }}</p></template><template v-else-if="usage"><img class="pack-companion" src="/assets/mokyu-pack.svg" alt="" width="100" height="100"><p class="packed-reading"><strong>{{ packed }}%</strong> {{ t('packedContentHint') }}</p><p class="field-help">{{ t('packsInScope', { count: usage.packs }) }}</p></template></section>
    <section class="surface overview-panel cream-panel"><div class="section-heading"><h2><Flower2 :size="19" />{{ t(admin ? 'tidyingNow' : 'yourLittleHomes') }}</h2><RouterLink v-if="admin" to="/maintenance" class="text-button">{{ t('maintenance') }}<ArrowUpRight :size="15" /></RouterLink></div><div v-if="admin && runtime.data.value?.work.length" class="work-glimpses"><RouterLink v-for="work in runtime.data.value.work" :key="work.id" class="work-glimpse" :to="{ path: '/tasks', query: { task: work.id } }"><span class="work-mark" :class="taskTone(work.kind)"><component :is="jobIcon(work.kind)" :size="18" /></span><div><strong>{{ t('task_' + work.kind) }}</strong><small>{{ t(work.state) }} · {{ t('processedItems', { count: work.processed }) }}</small></div><span class="work-state" :class="work.state" /></RouterLink></div><div v-else-if="admin" class="tidy-rest"><img src="/assets/mokyu-mochi.svg" alt="" width="106" height="104"><div><strong>{{ t('quietWorkroom') }}</strong><p>{{ t('quietWorkroomHint') }}</p></div></div><div v-else class="home-links"><RouterLink v-for="home in homes" :key="home.id" :to="'/media/' + home.id"><Package :size="17" />{{ home.name }}<ArrowUpRight :size="14" /></RouterLink></div></section>
    <section class="surface overview-panel lilac-panel"><div class="section-heading"><h2><Heart :size="19" />{{ t('growingCollection') }}</h2></div><TrendChart :points="capacity" :label="t('logicalMedia')" unit="bytes" /></section>
    <section class="surface overview-panel sky-panel"><template v-if="admin"><div class="section-heading"><h2><Activity :size="19" />{{ t('requestsOverTime') }}</h2><span class="field-help">{{ t('deploymentOnly') }}</span></div><TrendChart :points="requests" :label="t('requestsPerSecond')" unit="rate" /></template><template v-else><div class="section-heading"><h2><Package :size="19" />{{ t('storageMadeGentle') }}</h2></div><p class="insight-note">{{ t('memberStorageHint') }}</p><RouterLink class="button" :to="{ path: '/storage', query: scope }">{{ t('exploreStorage') }}<ArrowUpRight :size="16" /></RouterLink></template></section>
  </div>
</template>
