<script setup lang="ts">
import ErrorNotice from '../components/ErrorNotice.vue'
import { computed, onBeforeUnmount, ref } from 'vue'
import { onBeforeRouteLeave } from 'vue-router'
import { useQuery } from '@tanstack/vue-query'
import { TabsRoot, TabsList, TabsTrigger, TabsContent } from 'reka-ui'
import { HeartPulse, Database, Cpu, Cloud, Search, KeyRound, Copy, RefreshCw } from 'lucide-vue-next'
import { api, write, bytes } from '../api/client'
import type { components } from '../api/schema'
import { t, date } from '../app/i18n'
import { secure } from '../app/security'
import { copy, errorText, notify, report } from '../app/feedback'
import UiDialog from '../components/ui/UiDialog.vue'
import UiSelect from '../components/ui/UiSelect.vue'
import UiCheckbox from '../components/ui/UiCheckbox.vue'
const tab = ref('runtime'), search = ref(''), section = ref(''), busy = ref(false)
const status = useQuery({ queryKey: ['service-status'], queryFn: ({ signal }) => api<components['schemas']['ServiceStatus']>('/api/service/status', { signal }), refetchInterval: 5000 })
const config = useQuery({ queryKey: ['service-config'], enabled: computed(() => tab.value === 'config'), queryFn: ({ signal }) => api<components['schemas']['ConfigField'][]>('/api/service/config', { signal }) })
const counter = computed(() => Object.fromEntries((status.data.value?.counters || []).map(row => [row.key, row.value])))
const queues = computed(() => Object.entries((status.data.value?.backend_queues || {}) as Record<string, { limit: number; running: number; queued: Record<string, number>; oldest_wait_seconds: number }>))
const catalog = computed(() => status.data.value?.catalog as { phase?: string; scanned?: string; last_error?: string } | undefined)
const sections = computed(() => [{ value: '', label: t('allConfigSections') }, ...[...new Set((config.data.value || []).map(row => row.key.split('.')[0]!))].map(value => ({ value, label: value }))])
const fields = computed(() => (config.data.value || []).filter(row => (!section.value || row.key.startsWith(section.value + '.')) && `${row.key} ${row.value}`.toLowerCase().includes(search.value.toLowerCase())))
const secret = ref(''), acknowledged = ref(false), input = ref<HTMLInputElement | null>(null)
const secretOpen = computed({ get: () => !!secret.value, set: v => { if (!v && acknowledged.value) secret.value = '' } })
async function generate() { busy.value = true; try { const result = await secure(() => write<components['schemas']['KeyMaterial']>('/api/service/key-material', {})); acknowledged.value = false; secret.value = result.secret } catch (e) { report(e) } finally { busy.value = false } }
async function copySecret() { try { await navigator.clipboard.writeText(secret.value); notify(t('copied')) } catch { input.value?.focus(); input.value?.select(); notify(t('secretSelect')) } }
function unloading(event: BeforeUnloadEvent) { if (secret.value && !acknowledged.value) { event.preventDefault(); event.returnValue = '' } }
window.addEventListener('beforeunload', unloading)
onBeforeUnmount(() => { secret.value = ''; window.removeEventListener('beforeunload', unloading) })
onBeforeRouteLeave(() => { if (secret.value && !acknowledged.value) { notify(t('saveSecretHint')); return false } })
function diagnostic() { copy(JSON.stringify({ service: status.data.value, configuration: config.data.value }, null, 2), t('diagnosticCopied')) }
</script>
<template><div class="page-heading"><div><p class="eyebrow">{{ t('serviceEyebrow') }}</p><h1>{{ t('service') }}</h1><p>{{ t('serviceHint') }}</p></div><div class="heading-actions"><button @click="diagnostic"><Copy :size="16" />{{ t('copyDiagnostics') }}</button><button class="icon-button" :aria-label="t('refresh')" @click="status.refetch(); config.refetch()"><RefreshCw :size="17" /></button></div></div><ErrorNotice v-if="status.error.value" :error="status.error.value" />
  <TabsRoot v-model="tab"><TabsList class="tabs-list" :aria-label="t('service')"><TabsTrigger value="runtime" class="tab-trigger">{{ t('liveRuntime') }}</TabsTrigger><TabsTrigger value="config" class="tab-trigger">{{ t('runtimeConfig') }}</TabsTrigger><TabsTrigger value="tools" class="tab-trigger">{{ t('administratorTools') }}</TabsTrigger></TabsList>
    <TabsContent value="runtime"><div class="service-metrics"><section class="surface service-metric rose"><HeartPulse :size="25" /><span>{{ t('serviceMode') }}</span><strong>{{ status.data.value ? t(status.data.value.maintenance ? 'recoveryMode' : 'serviceOnline') : '—' }}</strong><small v-if="status.data.value">Mokyu {{ status.data.value.version }}</small></section><section class="surface service-metric lilac"><Cpu :size="25" /><span>{{ t('processMemory') }}</span><strong>{{ counter.rss_bytes && counter.rss_bytes !== 'null' ? bytes(Number(counter.rss_bytes)) : '—' }}</strong><small>{{ t('activeStreams', { count: counter.active_streams || '0' }) }}</small></section><section class="surface service-metric mint"><Database :size="25" /><span>{{ t('databasePool') }}</span><strong>{{ counter.db_pool_idle || '—' }} / {{ counter.db_pool_size || '—' }}</strong><small>{{ t('idleConnections') }}</small></section></div><div class="service-queues"><section v-for="[kind, queue] in queues" :key="kind" class="surface queue-card"><div class="section-heading"><h2><Cloud :size="19" />{{ t('queue_' + kind) }}</h2><span class="badge">{{ queue.running }} / {{ queue.limit }}</span></div><p class="field-help">{{ t('queueHint') }}</p><dl class="facts"><dt>{{ t('foregroundQueue') }}</dt><dd>{{ queue.queued.foreground }}</dd><dt>{{ t('uploadQueue') }}</dt><dd>{{ queue.queued.upload }}</dd><dt>{{ t('maintenanceQueue') }}</dt><dd>{{ queue.queued.maintenance }}</dd><dt>{{ t('oldestWait') }}</dt><dd>{{ t('secondsShort', { value: queue.oldest_wait_seconds }) }}</dd></dl></section></div><section class="surface recovery-card"><div class="section-heading"><h2>{{ t('indexReadiness') }}</h2></div><dl class="facts"><dt>{{ t('catalogState') }}</dt><dd>{{ t('catalog_' + (catalog?.phase || 'unknown')) }}</dd><dt>{{ t('catalogScanned') }}</dt><dd>{{ catalog?.scanned || '—' }}</dd><dt>{{ t('inventoryAsOf') }}</dt><dd>{{ status.data.value?.inventory_as_of ? date(status.data.value.inventory_as_of) : t('collectingInsights') }}</dd><dt>{{ t('startedAt') }}</dt><dd>{{ status.data.value?.started_at ? date(status.data.value.started_at) : '—' }}</dd></dl><p v-if="catalog?.last_error || status.data.value?.inventory_error" class="error">{{ catalog?.last_error || status.data.value?.inventory_error }}</p><p v-if="status.data.value?.inventory_stale" class="field-help">{{ t('snapshotStale') }}</p></section><section class="surface recovery-card"><details><summary>{{ t('runtimeCounters') }}</summary><dl class="runtime-counters"><template v-for="row in status.data.value?.counters" :key="row.key"><dt>{{ row.key }}</dt><dd>{{ row.value }}</dd></template></dl></details></section></TabsContent>
    <TabsContent value="config"><div class="info-callout"><p>{{ t('runtimeConfigHint') }}</p></div><ErrorNotice v-if="config.error.value" :error="config.error.value" /><section class="surface config-board"><div class="task-filters"><UiSelect v-model="section" :options="sections" :label="t('configSection')" /><label class="inline-search"><Search :size="17" /><input v-model="search" :placeholder="t('searchConfiguration')" :aria-label="t('searchConfiguration')"></label></div><div class="config-fields"><article v-for="row in fields" :key="row.key"><div><code>{{ row.key }}</code><span class="badge">{{ t('configSource_' + row.source) }}</span></div><strong>{{ row.value === '[redacted]' ? t('redactedValue') : row.value === 'null' ? t('notConfigured') : row.value }}</strong><small>{{ t(row.restart ? 'restartRequired' : 'liveSetting') }}</small></article></div><p v-if="config.data.value && !fields.length" class="field-help">{{ t('noConfigMatches') }}</p></section></TabsContent>
    <TabsContent value="tools"><section class="surface key-material-card"><span class="key-symbol"><KeyRound :size="28" /></span><h2>{{ t('generateKeyMaterial') }}</h2><p>{{ t('keyMaterialHint') }}</p><button class="primary" :disabled="busy" @click="generate"><KeyRound :size="17" />{{ t('generateKeyMaterial') }}</button></section></TabsContent>
  </TabsRoot><UiDialog v-model:open="secretOpen" :title="t('saveSecret')" :description="t('keyMaterialHint')" :busy="!acknowledged"><label>{{ t('secretValue') }}<input ref="input" :value="secret" readonly autocomplete="off" spellcheck="false"></label><button @click="copySecret"><Copy :size="16" />{{ t('copySecret') }}</button><div class="detail-section"><UiCheckbox v-model="acknowledged" :label="t('secretSaved')" /></div><template #footer><button class="primary" :disabled="!acknowledged" @click="secretOpen = false">{{ t('done') }}</button></template></UiDialog>
</template>
