<script setup lang="ts">
import ErrorNotice from './ErrorNotice.vue'
import { computed, ref, watch } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { Play, Pause, Download, ArrowUpRight, Copy } from 'lucide-vue-next'
import { api, write, params, queries } from '../api/client'
import type { components } from '../api/schema'
import { t, date } from '../app/i18n'
import { report, copy, errorText } from '../app/feedback'
import { jobIcon, type Job } from '../app/maintenance'
import { taskTone } from '../app/insights'
import UiDialog from './ui/UiDialog.vue'
import UiSelect from './ui/UiSelect.vue'
import MaintenanceConfirm from './MaintenanceConfirm.vue'
const props = defineProps<{ id: string }>(), open = defineModel<boolean>('open', { required: true })
const busy = ref(false), confirm = ref(false), code = ref(''), after = ref(''), selected = ref(''), objectAfter = ref<[string, string] | null>(null)
const job = useQuery({ queryKey: ['task', () => props.id], enabled: computed(() => open.value && !!props.id), queryFn: ({ signal }) => api<Job>(`/api/tasks/${props.id}`, { signal }), refetchInterval: q => ['queued', 'running'].includes(q.state.data?.state || '') ? 3000 : false })
const detail = computed(() => (job.data.value?.detail || {}) as Record<string, any>)
const issues = useQuery({ queryKey: ['task-issues', () => props.id, code, after], enabled: computed(() => open.value && job.data.value?.kind === 'integrity'), queryFn: ({ signal }) => api<components['schemas']['IssuePage']>(`/api/tasks/${props.id}/issues?` + params({ code: code.value || undefined, after: after.value || undefined }), { signal }), refetchInterval: computed(() => job.data.value?.state === 'running' ? 5000 : false) })
const related = useQuery({ queryKey: ['issue-objects', () => props.id, selected, objectAfter], enabled: computed(() => open.value && !!selected.value), queryFn: ({ signal }) => api<components['schemas']['IssueObjects']>(`/api/tasks/${props.id}/issues/${selected.value}/objects?` + params({ after: objectAfter.value ? JSON.stringify(objectAfter.value) : undefined }), { signal }) })
const groups = computed(() => [{ value: '', label: t('allIssues') }, ...Object.entries(issues.data.value?.groups || {}).map(([value, count]) => ({ value, label: `${value} (${count})` }))])
watch(() => props.id, () => { code.value = ''; after.value = ''; selected.value = ''; objectAfter.value = null })
watch(code, () => { after.value = ''; selected.value = '' })
watch(selected, () => { objectAfter.value = null })
const summary = computed(() => ['mode', 'phase', 'chunks_checked', 'objects_checked', 'issues', 'candidates', 'bytes', 'unrecognized'].filter(key => detail.value[key] != null).map(key => ({ key, value: String(detail.value[key]) })))
async function change(action: string) { busy.value = true; try { await write(`/api/tasks/${props.id}/actions`, { action }); await job.refetch(); await queries.invalidateQueries({ queryKey: ['maintenance'] }); await queries.invalidateQueries({ queryKey: ['jobs'] }) } catch (e) { report(e) } finally { busy.value = false } }
</script>
<template><UiDialog v-model:open="open" :title="t('taskDetails')" :description="t('taskDetailHint')" drawer><ErrorNotice v-if="job.error.value" :error="job.error.value" /><template v-if="job.data.value"><div class="task-hero"><span class="policy-icon" :class="taskTone(job.data.value.policy)"><component :is="jobIcon(job.data.value.policy)" :size="30" /></span><div><h2>{{ t('task_' + job.data.value.policy) }}</h2><span class="badge">{{ t(job.data.value.state) }}</span></div><button class="icon-button" :aria-label="t('copyTaskId')" @click="copy(id)"><Copy :size="16" /></button></div><div class="task-count"><strong>{{ job.data.value.processed }}</strong><span>{{ t('itemsProcessed') }}</span></div><p v-if="job.data.value.blocked" class="info-callout">{{ t('blocked_' + job.data.value.blocked) }}</p><p v-if="job.data.value.error" class="error task-error" role="alert">{{ job.data.value.error }}</p><dl class="facts"><dt>{{ t('taskActor') }}</dt><dd>{{ job.data.value.created_by }} · {{ t('source_' + job.data.value.source) }}</dd><dt>{{ t('created') }}</dt><dd>{{ date(job.data.value.created_at) }}</dd><dt>{{ t('startedAt') }}</dt><dd>{{ job.data.value.started_at ? date(job.data.value.started_at) : '—' }}</dd><dt>{{ t('updated') }}</dt><dd>{{ date(job.data.value.updated_at) }}</dd><template v-if="job.data.value.bucket_id"><dt>{{ t('buckets') }}</dt><dd>{{ job.data.value.bucket_name || job.data.value.bucket_id }}</dd></template><template v-for="row in summary" :key="row.key"><dt>{{ t('job_' + row.key) }}</dt><dd>{{ row.value }}</dd></template></dl>
    <div class="actions"><button v-if="['queued', 'running'].includes(job.data.value.state)" :disabled="busy" @click="change('pause')"><Pause :size="16" />{{ t('pauseTask') }}</button><button v-if="['paused', 'failed'].includes(job.data.value.state)" :disabled="busy || !!job.data.value.blocked" @click="change('resume')"><Play :size="16" />{{ t('resumeTask') }}</button><a v-if="job.data.value.kind === 'integrity' && job.data.value.state === 'completed'" class="button" :href="`/api/tasks/${id}/report`" download><Download :size="16" />{{ t('downloadReport') }}</a><button v-if="job.data.value.kind === 'sweep' && job.data.value.state === 'completed' && detail.dry_run" class="danger" @click="confirm = true">{{ t('reviewSweep') }}</button></div>
    <section v-if="job.data.value.kind === 'integrity'" class="detail-section"><div class="section-heading"><h3>{{ t('inspectionIssues') }}</h3><UiSelect v-model="code" :options="groups" :label="t('issueGroup')" /></div><ErrorNotice v-if="issues.error.value" :error="issues.error.value" /><p v-if="issues.data.value && !issues.data.value.issues.length" class="field-help">{{ t(job.data.value.state === 'completed' ? 'inspectionClean' : 'noIssuesYet') }}</p><div class="issue-list"><article v-for="issue in issues.data.value?.issues" :key="issue.id"><span class="badge">{{ issue.code }}</span><p v-if="issue.object_key" class="break-path">{{ issue.object_key }}</p><p v-if="issue.chunk_id" class="field-help">{{ t('chunkNumber', { id: issue.chunk_id }) }}</p><button @click="selected = selected === issue.id ? '' : issue.id">{{ t('affectedFiles') }}</button><template v-if="selected === issue.id"><ErrorNotice v-if="related.error.value" :error="related.error.value" /><div class="issue-files"><RouterLink v-for="object in related.data.value?.objects" :key="object.bucket_id + object.key" :to="{ path: '/media/' + object.bucket_id, query: { object: object.key, version: object.version } }" @click="open = false">{{ object.bucket }} / {{ object.key }}<ArrowUpRight :size="14" /></RouterLink><p v-if="related.data.value && !related.data.value.objects.length" class="field-help">{{ t('noVisibleReferences') }}</p><button v-if="related.data.value?.next" @click="objectAfter = related.data.value.next">{{ t('nextPage') }}</button></div></template></article></div><div class="table-footer"><button v-if="after" @click="after = ''">{{ t('firstPage') }}</button><button v-if="issues.data.value?.next_after" @click="after = issues.data.value.next_after">{{ t('nextPage') }}</button></div></section>
    <details class="task-technical"><summary>{{ t('technicalDetails') }}</summary><code>{{ id }}</code><pre>{{ JSON.stringify(detail, null, 2) }}</pre></details>
  </template></UiDialog><MaintenanceConfirm v-model:open="confirm" operation="sweep" :input="{ task_id: id }" /></template>
